phone:
    path:     /
    defaults: { _controller: "AcmeMainBundle:Phone:index" }

phone_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeMainBundle:Phone:show" }

phone_new:
    path:     /new
    defaults: { _controller: "AcmeMainBundle:Phone:new" }

phone_create:
    path:     /create
    defaults: { _controller: "AcmeMainBundle:Phone:create" }
    requirements: { _method: post }

phone_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeMainBundle:Phone:edit" }

phone_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeMainBundle:Phone:update" }
    requirements: { _method: post|put }

phone_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeMainBundle:Phone:delete" }
    requirements: { _method: post|delete }
