# app/config/security.yml
security:
    encoders:
        Acme\MainBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: AcmeMainBundle:User, property: username }

    firewalls:
        default:
            pattern:    ^/admin
            anonymous: ~
            http_basic: ~
            logout:
                path:   /logout
                target: /
                invalidate_session: false
                    
    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY  }