<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectedUserTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectedUserTypeRepository extends EntityRepository
{
}
