<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * funeralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class funeralRepository extends EntityRepository
{
}
