<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PallbearersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PallbearersRepository extends EntityRepository
{
}
